version: '3.5'

services:
  driver:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${PWD}:/app
    working_dir: /app/tests/Dummy
    command:
      - -c
      - |
        touch database/development.sqlite
        [ ! -f vendor/autoload ] && composer install
        sh $$@
    depends_on:
      - database
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=123456
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
  database:
    build: 
      dockerfile: Dockerfile.db
      context: .
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=mysqlroot
